### ISSUE TITLE
SCC2691 reset polarity

### ISSUE THREAD

**Issue by DavidJRichards** [lenzjo/MECB-SYS-IO#1]
Greetings, There appears to be a discrepancy between the reset polarities of the MECB bus and the requirement of the SCC2691. The bus reset is active low but the SCC2691 reset input is active high. Have I misunderstood the documents or is this a schematic error? I have yet to test this on any hardware but am looking forward to trying your board sortly. Best regards, David.

**Comment by lenzjo** [comment]
Sorry about that. Typical schoolboy error. I have updated the repository with an untested fix, but it should work.

**Comment by DavidJRichards** [comment]
Thanks for the updated files. The value of R6, 1M ohm,  on the updated schematic seems high. I would expect to see something around a few K ohms in that position. D

**Comment by lenzjo** [comment]
1M has worked for me in the past on different projects. I have yet to try it in this instance as I am waiting for the PCBs. As I said in the README, I have not had time to fully test the pcb yet as I have little free time.
