### ISSUE TITLE
Keyboard connector signal pin holes size

### ISSUE THREAD

**Issue by DavidJRichards** [lenzjo/MECB-SYS-IO#2]
The mini DIN connectors I have seen have small flat pins which are larger than the holes on the PCB. Drilling out to suit these could result in another problem since a PCB track is routed in the space between the pins holes. However, although tight the pins just fit as is.

**Comment by lenzjo** [comment]
I get my mini DIN connectors from [ebay](https://www.ebay.co.uk/itm/384011894850?_skw=mini+pcb+din+connector&itmmeta=01J7ZZA9JCH8KW6WJZ6724GCNF&hash=item5968e48042:g:t00AAOSwW7RlF4pB&itmprp=enc%3AAQAJAAAA8HoV3kP08IDx%2BKZ9MfhVJKkRUYBSfUWTITisKQGr7dbv%2FblQNA5vGT7RKxQ9%2BFXJZpQdWYfnG6vGN1lFUvCamh44fv84D%2FElx7tk6M1Z4tKXEjtNu8JtUsKOQ0OG7TFoyWlYnpSb7ZUrKYCXZnNiorEV6635GwzbwfzDa6tuQJQfu%2BjKRfSfzskAyx4yacMTeYWiW5ZtkxwwmzCCqBV3ljEMvG1ZsY9QozEzTe4g1UpdERPYLYe0%2BGhm7HGSrTBUK8OS3xJgLjUk%2BAmPI%2FL9IYXn60o7TdgH%2BWliy1sz%2F%2BLB9rp6bi1VW%2Fu9vh%2FLFnlszw%3D%3D%7Ctkp%3ABFBMpJmp_79k). Or just do a search for mini DIN pcb connector. The footprint I used was from the standard Kicad library.
