### ISSUE TITLE
Uses undocumented connector pin A13 for read/write signal

### ISSUE THREAD

**Issue by DavidJRichards** [lenzjo/MECB-SYS-IO#3]
This board depends on bus signal A13 for Read / Write signal to the 6522 VIA
This pin is not implemented in the MECB
Is the intention to patch through the CPU R/W signal for use here?
Would it be possible to use the ECB!WR here instead?

**Comment by lenzjo** [comment]
"This board depends on bus signal A13 for Read / Write signal to the 6522 VIA"
Correct

"This pin is not implemented in the MECB"
Correct, but my boards are to be used with MY [version](https://github.com/lenzjo/MECB-Backplane) of the MECB back-plane which also implements:
C11 - KYBD_CLK
A12 - KYBD_DATA
A30 - ECB_TxD
C16 - ECB_RTS
A17 - ECB_RxD
C19 - ECB_CTS
A28 - COMP_VID
A31 - SND

"Is the intention to patch through the CPU R/W signal for use here?"
Yes, if you are not using my [backplane](https://github.com/lenzjo/MECB-Backplane)

"Would it be possible to use the ECB!WR here instead?"
Probably
