### ISSUE TITLE
Board power track defect

### ISSUE THREAD

**Issue by DavidJRichards** [lenzjo/MECB-SYS-IO#4]
Greetings, I found a problem, not sure of the cause.

The SYS-IO board I had made from gerbers dated 19th July 2024 suffers from a problem where some of the nodes which should connect to +5V are not connected to the main 5V power input connector.

These nodes are all connected together but not to +5V incoming:
D1 anode
U1 pin 20
U5 pin 20
U5 pin 24
R1 +Ve
R2 +ve
Cx +ve
Cx +ve

It appears that a track is missing rather than a broken connection but I can't be sure not having seen the track layout in the cad system. All five boards I have seem to have the same problem. 
Other connections seem ok, VIA now works with incoming DC applied with bodge wire.

Best regards, David.

**Comment by lenzjo** [comment]
Missing trace: ATtiny261A - U6 pin 15 -> C4 pin 1 +5v. That will connect all of the above to +5v.

FYI: There has been at least one, maybe two updates since the 19th July, fixing stuff. One that springs to mind is the GND on the battery was not connected to GND.
