### ISSUE TITLE
Keyboard clock signal routing error

### ISSUE THREAD

**Issue by DavidJRichards** [lenzjo/MECB-SYS-IO#5]
The keyboard clock signal is connected to the ATtiny261A BP2 (pin3) the supplied firmware is expecting the keyboard clock on PB3 (pin 4)

A simple fix for this problem is to connect pins 3 & 4 though a better solution is to isolate PB2 and re-route the clock and pull-up resistor freeing PB2 for other uses.

No signals were being received before making this change.
To test the keyboard it is adequate to connect PIA_CA1 with PIA_CA2 to supply the necessary handshake.
hth David.

**Comment by lenzjo** [comment]
Thank you David, I've updated the gerbers etc.
